[theme]
primaryColor = "#7267EF"
backgroundColor = "#f6f7fb"
secondaryBackgroundColor = "#ffffff"
textColor = "#333333"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false